# NumPy Programming Assignment

Part 1: Smart Array Factory
Task: Create a function that allows students to generate specific array types quickly using built-in NumPy methods.


In [10]:
import numpy as np

def array_factory(mode, shape, value=None):
    """
    Creates various NumPy arrays based on the mode.
    - 'zeros': Array filled with 0.
    - 'ones': Array filled with 1.
    - 'full': Array filled with a specified 'value'.
    - 'identity': A square identity matrix of size 'shape'.
    """
    # TODO: Students implement logic here
    
    if mode=="zeros":
        return np.zeros(shape)
    
    elif mode=="ones":
        return np.ones(shape,value)
    
    elif mode == "full":
        return np.full(shape, value)

    elif mode == "identity":
        return np.eye(shape)
    

    else:
        raise ValueError("Invalid mode. Choose: zeros, ones, full, identity")

In [11]:
print(array_factory("zeros", (2, 3)))

[[0. 0. 0.]
 [0. 0. 0.]]


In [12]:
print(array_factory("ones", (2, 3)))

[[1. 1. 1.]
 [1. 1. 1.]]


In [13]:
print(array_factory("full", (2, 3), 7))

[[7 7 7]
 [7 7 7]]


In [15]:
print(array_factory("identity", 4))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


Part 2: The secure_reshape_and_stack Function.

This function demonstrates how to handle data integration by transforming a flat data structure into a matrix and then combining it with an existing dataset

In [21]:
import numpy as np

def secure_reshape_and_stack(data1, data2, new_shape):
    """
    1. Validates and converts inputs to NumPy arrays.
    2. Reshapes the first dataset to a specific dimension.
    3. Vertically stacks both datasets into one matrix.
    """
    try:
        arr1 = np.array(data1)
        arr2 = np.array(data2)

        reshaped_arr1 = arr1.reshape(new_shape)

        combined_dataset = np.vstack((reshaped_arr1, arr2))

        return combined_dataset

    except ValueError as e:
        raise ValueError(f"Company-grade Error: {e}")




In [29]:
# Regional Branch A
branch_a = [1, 2, 3, 4, 5, 6]

# Regional Branch B
branch_b = [
    [7, 8, 9],
    [10, 11, 12]
]

# Reshape A to 2x3 and stack with B
final_report = secure_reshape_and_stack(
    branch_a,
    branch_b,
    (2, 3)
)

print(final_report)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [22]:
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([[5, 6],
                 [7, 8]])

new_shape = (2, 2)

print(secure_reshape_and_stack(arr1, arr2, new_shape))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


part-3 The apply_threshold Function.

This function demonstrates Conditional Access and Modification, which are primarily used in data cleaning and processing. It follows the logic of identifying specific elements based on a boolean condition and replacing them efficiently.

In [24]:
import numpy as np

def apply_threshold(arr, threshold, replacement_value=-1):
    """
    Finds elements satisfying a condition (>= threshold) 
    and replaces them with a new value.
    """

    # 1. Convert input to a numpy array
    arr = np.array(arr)

    # 2. Define the condition
    condition = arr >= threshold

    # 3. Apply modification using np.where()
    modified_arr = np.where(
        condition,
        replacement_value,
        arr
    )

    return modified_arr

In [25]:
v = np.array([1, 2, 3])

print(apply_threshold(v, 2, -20))

[  1 -20 -20]


TestCase

In [28]:
# Regional Branch A
branch_a = [1, 2, 3, 4, 5, 6]

# Regional Branch B
branch_b = [
    [7, 8, 9],
    [10, 11, 12]
]

# Reshape A to 2x3 and stack with B
final_report = secure_reshape_and_stack(
    branch_a,
    branch_b,
    (2, 3)
)

print(final_report)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [27]:
v= np.array([1,2,3])
apply_threshold(v,2,-20)


array([  1, -20, -20])