In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [25]:
import numpy as np


In [26]:
v1=np.array([12,23,45])
v2=np.array([1,2,7,3])
v3=np.array(4)


In [27]:
print(v1)
print(v2)
print(v3)

[12 23 45]
[1 2 7 3]
4


In [28]:
print(v1.shape)
print(v2.shape)
print(v3.shape)


(3,)
(4,)
()


In [29]:
class Student:
    def __init__(self,name,age):
    
        self._name=name
        self.age=age     
        
    @property #read only function
    def name(self):
        return f"{self._name}"   

In [30]:
s1=Student("Hassan",21)
s1.name

'Hassan'

In [32]:
vec = np.array([1, 2, 3, 4, 5, 6])
mat = vec.reshape((2, 3))
print(mat)

[[1 2 3]
 [4 5 6]]


In [34]:
vec=np.array([1,2,3,4])
mat=vec.reshape((vec.shape[0]))

In [36]:
mat=vec.reshape((vec.shape[0],1))
print(mat)

[[1]
 [2]
 [3]
 [4]]


In [37]:
def array_reshape(arr,row=-1,cols=-1):
    
    try:
        arr=np.array(arr)
        return arr.reshape((row,cols))
    except Exception as e:
        raise ValueError("Invalid Reshape {e}")

In [38]:
vec=[1,2,3,4,5,6]
print("test 1(1*2 Matrix:) :",array_reshape(vec,2,3))

test 1(1*2 Matrix:) : [[1 2 3]
 [4 5 6]]


object m ,string ,float,int ,bool,

In [43]:
mat= np.array([[1,2,3],[4,5,6]])
mat.shape

(2, 3)

In [48]:
import numpy as np

mat = np.array([[1, 5, 2], [23, 4, True]])

fmat = mat.astype(int)

print(fmat)
print(fmat.dtype)

[[ 1  5  2]
 [23  4  1]]
int64


In [51]:
v=np.array([3,4,6,2,7])
print(v[2])
print(v[-1])

6
7


In [ ]:
m=np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9],
    [0,0,0]
])

print(m[1][2])

6


In [59]:
m[1:3,0:2]

array([[4, 5],
       [7, 8]])

In [63]:
mat=np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9],
    [0,0,0]
])
mat_transpose=mat.T
print(mat_transpose)



[[1 4 7 0]
 [2 5 8 0]
 [3 6 9 0]]


In [64]:
z=np.zeros((4,4))
z

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [66]:
o=np.ones((3,3))
o

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [72]:
f=np.full((3,3),5)
f

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [73]:
e=np.empty((3,3))
e

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [79]:
angles=np.arange(0,361,90)
angles

array([  0,  90, 180, 270, 360])

In [82]:
vec=np.linspace(0,10, num=10)
vec

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [ ]:
vec=np.identity(3,dtype="float32")
vec

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)

In [84]:
import random
np.random.random( (3,3))

array([[0.1334698 , 0.61889297, 0.19952273],
       [0.03472366, 0.51713412, 0.36032916],
       [0.10303242, 0.24959443, 0.42359369]])